services:
  mongo:
    image: mongo:6
    # container_name: mongo   # optional
    restart: always
    # no host port for Mongo to avoid conflicts
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      # backend talks to Mongo using the service name "mongo" on the internal Docker network
      - MONGO_URI=mongodb://mongo:27017/comp3123_assignment2
      - JWT_SECRET=supersecretjwtkey
      - PORT=5000
    ports:
      # expose backend to your HOST so the browser can hit http://localhost:5000
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      # ðŸ‘‡ map container's /app/uploads to your local backend/uploads folder
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    environment:
      # IMPORTANT: this is used by the React app in the browser,
      # so it must point to localhost, not "backend"
      - REACT_APP_API_URL=http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:

